
import { FineTuningRecord } from '../types';

/**
 * Converts internal feedback records to the standard Alpaca format used for LLM training.
 */
export const convertToAlpacaFormat = (records: FineTuningRecord[]) => {
    return records
        .filter(r => r.score === 1) // Only use positive feedback for SFT
        .map(r => ({
            instruction: r.prompt,
            input: r.context, // RAG Context goes here
            output: r.response
        }));
};

/**
 * Generates a ready-to-run Python script for Unsloth (Fastest LoRA library).
 * This script is customized based on the user's current model settings.
 */
export const generateUnslothScript = (modelName: string, numEpochs: number = 1) => {
    return `
# ---------------------------------------------------------
# Rayan Ham-Afza Auto-Trainer Script
# Generated by Local RAG Assistant
# Library: Unsloth (2x faster, 60% less memory)
# ---------------------------------------------------------

from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# 1. Configuration
max_seq_length = 2048
dtype = None # Auto detection
load_in_4bit = True 

# 2. Load Base Model (${modelName})
print("⏳ Loading Model: ${modelName}...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "${modelName}", 
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# 3. Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # LoRA Rank
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# 4. Load Dataset (Exported from App)
print("📂 Loading Dataset: dataset.json...")
dataset = load_dataset("json", data_files="dataset.json", split="train")

# 5. Formatting Function
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        text = alpaca_prompt.format(instruction, input, output) + tokenizer.eos_token
        texts.append(text)
    return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched = True)

# 6. Training
print("🚀 Starting Training (${numEpochs} Epochs)...")
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, 
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # Adjusted for demo
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

trainer.train()

# 7. Save Model
print("💾 Saving LoRA Adapters...")
model.save_pretrained("lora_model")
print("✅ Training Complete! Use 'ollama create' to import.")
`;
};
